MOUSEKEY_ENABLE = no     # Mouse keys
RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE = yes # Allow RGB underlight to be controlled by a separate script.
VIA_ENABLE      = yes    # Enable VIA
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
WPM_ENABLE      = yes
SRC += oled-bongocat.c
OPT_DEFS += -DLEFTCAT
TAP_DANCE_ENABLE = yes
