#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// tap dance declarations
// enum {
//     TD_SCLN,
// };

// tap dance definitions
// qk_tap_dance_action_t tap_dance_actions[] = {
//     [TD_SCLN] = ACTION_TAP_DANCE_DOUBLE(KC_SCLN, KC_COLN),
// };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[0] = LAYOUT_split_3x6_3(
KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,   KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G,  KC_H, KC_J, KC_K, KC_L, KC_SCLN/*TD(TD_SCLN)*/, KC_QUOT,
KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ESC,
                KC_LGUI, LT(1,KC_TAB), KC_SPC, KC_ENT, MO(2), KC_RALT),


[1] = LAYOUT_split_3x6_3(
KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
KC_LCTL, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_F12,
KC_LSFT, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
                KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, MO(3), KC_RALT),

[2] = LAYOUT_split_3x6_3(
KC_TAB, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSPC,
KC_LCTL, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_NO, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS, KC_GRV,
KC_LSFT, KC_LT, KC_GT, KC_LBRC, KC_RBRC, KC_NO, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE, KC_TILD,
                KC_LGUI, MO(3), KC_SPC, KC_ENT, KC_TRNS, KC_RALT),

[3] = LAYOUT_split_3x6_3(
RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, GUI_OFF, GUI_ON, KC_NO,
RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, AG_SWAP, AG_NORM, KC_NO,
RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                KC_LGUI, KC_TRNS, KC_TRNS, KC_ENT, KC_TRNS, KC_RALT)
};


// per key tapping term settings
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    // switch through keycode
    switch (keycode) {
        case LGUI_T(KC_A):
            return TAPPING_TERM + 30;
        case LGUI_T(KC_SCLN):
            return TAPPING_TERM + 30;
        case LALT_T(KC_S):
            return TAPPING_TERM + 20;
        case RALT_T(KC_L):
            return TAPPING_TERM + 20;
        default:
            return TAPPING_TERM;
    }
}

enum combo_events {
    LANG_COMB,
    JKL_ENT,
    UIO_ESC,
    KLSCLN_TAB,

    // math
    UI_EQL,
    JK_MINS,
    MCOM_UNDS,
    JL_PLUS,

    // parenthese
    SCLNU_LBRC,
    SCLNI_RBRC,
    SCLNJ_LPRN,
    SCLNK_RPRN,
    SCLNM_LCBR,
    SCLNCOM_RCBR,

    COMBO_LENGTH
};

uint16_t COMBO_LEN = COMBO_LENGTH;

const uint16_t PROGMEM test_combo1[] = {KC_A, KC_B, COMBO_END};
const uint16_t PROGMEM jkl_ent[] = {KC_J, KC_K, KC_L, COMBO_END};
const uint16_t PROGMEM uio_esc[] = {KC_U, KC_I, KC_O,   COMBO_END};
const uint16_t PROGMEM klScln_tab[] = {KC_K, KC_L, KC_SCLN, COMBO_END};

const uint16_t PROGMEM ui_eql[] = {KC_U, KC_I, COMBO_END};
const uint16_t PROGMEM jk_mins[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM mcom_unds[] = {KC_M, KC_COMM, COMBO_END};
const uint16_t PROGMEM jl_plus[] = {KC_J, KC_L, COMBO_END};

const uint16_t PROGMEM sclnu_lbrc[] = {KC_SCLN, KC_U, COMBO_END};
const uint16_t PROGMEM sclni_rbrc[] = {KC_SCLN, KC_I, COMBO_END};
const uint16_t PROGMEM sclnj_lprn[] = {KC_SCLN, KC_J, COMBO_END};
const uint16_t PROGMEM sclnk_rprn[] = {KC_SCLN, KC_K, COMBO_END};
const uint16_t PROGMEM sclnm_lcbr[] = {KC_SCLN, KC_M, COMBO_END};
const uint16_t PROGMEM sclncom_rcbr[] = {KC_SCLN, KC_COMM, COMBO_END};

combo_t key_combos[] = {
    [LANG_COMB] = COMBO(test_combo1, KC_DOT),
    [JKL_ENT] = COMBO(jkl_ent, KC_ENT),
    [UIO_ESC] = COMBO(uio_esc, KC_ESC),
    [KLSCLN_TAB] = COMBO(klScln_tab, KC_TAB),

    // math
    [UI_EQL] = COMBO(ui_eql, KC_EQL),
    [JK_MINS] = COMBO(jk_mins, KC_MINS),
    [MCOM_UNDS] = COMBO(mcom_unds, KC_UNDS),
    [JL_PLUS] = COMBO(jl_plus, KC_PLUS),

    // parenthese
    [SCLNU_LBRC] = COMBO(sclnu_lbrc, KC_LBRC),
    [SCLNI_RBRC] = COMBO(sclni_rbrc, KC_RBRC),
    [SCLNJ_LPRN] = COMBO(sclnj_lprn, KC_LPRN),
    [SCLNK_RPRN] = COMBO(sclnk_rprn, KC_RPRN),
    [SCLNM_LCBR] = COMBO(sclnm_lcbr, KC_LCBR),
    [SCLNCOM_RCBR] = COMBO(sclncom_rcbr, KC_RCBR),

};

// combo_t key_combos[] = {
//     COMBO(test_combo1, KC_ESC),
//     COMBO(test_combo2, LCTL(KC_Z)), // keycodes with modifiers are possible too!
// };
